package com.dao;

import com.bean.user;
import com.bean.userExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    long countByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int deleteByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    List<user> selectByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int updateByExample(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_admin
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    int updateByPrimaryKey(user record);

    user selectuserByUsernameAndPassword(@Param("adminName") String adminName);
}
