package com.bean;

import java.util.Date;

public class user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.id
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.admin_number
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private String adminNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.admin_pwd
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private String adminPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.admin_name
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.login_pre_time
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private Date loginPreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.del_flg
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    private Integer delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.id
     *
     * @return the value of ms_admin.id
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.id
     *
     * @param id the value for ms_admin.id
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.admin_number
     *
     * @return the value of ms_admin.admin_number
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public String getAdminNumber() {
        return adminNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.admin_number
     *
     * @param adminNumber the value for ms_admin.admin_number
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setAdminNumber(String adminNumber) {
        this.adminNumber = adminNumber == null ? null : adminNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.admin_pwd
     *
     * @return the value of ms_admin.admin_pwd
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.admin_pwd
     *
     * @param adminPwd the value for ms_admin.admin_pwd
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd == null ? null : adminPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.admin_name
     *
     * @return the value of ms_admin.admin_name
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.admin_name
     *
     * @param adminName the value for ms_admin.admin_name
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.login_pre_time
     *
     * @return the value of ms_admin.login_pre_time
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public Date getLoginPreTime() {
        return loginPreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.login_pre_time
     *
     * @param loginPreTime the value for ms_admin.login_pre_time
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setLoginPreTime(Date loginPreTime) {
        this.loginPreTime = loginPreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.del_flg
     *
     * @return the value of ms_admin.del_flg
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    @Override
    public String toString() {
        return "user{" +
                "id=" + id +
                ", adminNumber='" + adminNumber + '\'' +
                ", adminPwd='" + adminPwd + '\'' +
                ", adminName='" + adminName + '\'' +
                ", loginPreTime=" + loginPreTime +
                ", delFlg=" + delFlg +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.del_flg
     *
     * @param delFlg the value for ms_admin.del_flg
     *
     * @mbg.generated Sat Sep 05 12:00:56 CST 2020
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }
}